blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('kanban', 'KanbanController');

Route::resource('user', 'UserController');

Route::resource('authorizer', 'AuthorizerController',['only' => ['store', 'destroy']]);

Route::resource('kbcolumn', 'KBColumnController',['only' => ['update', 'destroy']]);

Route::resource('card', 'CardController',['only' => ['store', 'update', 'destroy']]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

blog/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    public function user()
    {
        return $this->belongsTo('App\Kanban');
    }

    public function authorizer()
    {
        return $this->hasMany('App\Authorizer');
    }

    public function card()
    {
        return $this->hasMany('App\Card');
    }
}

blog/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{

    /**
     * Instantiate a new UserController instance.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = App\User::all();
        return view('user.index', compact('users'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\KBColumn  $kBColumn
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $public = App\Kanban::where([
            ['user_id','=', $user->id],
            ['visibility', '=', 'Oui']
        ]);

        $private = App\Kanban::where([
            ['user_id','=', $user->id],
            ['visibility', '=', 'Non']
        ])->get();

        $authorisations = App\Authorizer::where('user_id','=', Auth::id())->get();
        $invited = Array(count($authorisations));
        foreach ($authorisations as $autho){
            $kanban_invit = App\Kanban::findOrFail($autho->kanban_id);
            if ($kanban_invit->user_id != $user->id) {
                $invited[$autho->id] = $kanban_invit;
            }
        }
        unset($invited[0]);

        $cards = App\Card::where('user_id','=', Auth::id())->get();
        $columns = App\KBColumn::all();
        $kanbans = Array();
        $kanbans_names = Array();
        foreach ($columns as $column){
            $kanbans[$column->id] = $column->kanban_id;
            $kanban = App\Kanban::findOrFail($column->kanban_id);
            $kanbans_names[$column->id] = $kanban->title;
        }
        return view('user.show', compact('user', 'private', 'public', 'invited', 'cards', 'kanbans', 'kanbans_names'));
    }
}

blog/resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if(!Auth::guest())
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Utilisateurs des Turbo-Kanbans</div>
                    <div class="panel-body">
                            <div class="row">
                                <div class="container-fluid">
                                    <table class="table">
                                        <thead class="thead-dark">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Nom</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($users as $user)
                                            <tr>
                                                <td>{{$user->id}}</td>
                                                <td><a href="{{route('user.show', ['id' => $user->id])}}">{{$user->name}}</a></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        @else
            <h1>Vous n'êtes pas autorisé. Authentifiez-vous pour accéder à cette page.</h1>
        @endif
    </div>
@stop

blog/resources/views/user/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <h1>{{$user->name}}</h1>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @if(Auth::id() == $user->id)
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Mes kanbans privés
                        <a class="btn btn-default" href="{{ route('kanban.create') }}"><span class="glyphicon glyphicon-plus"></span></a>
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nom</th>
                                <th scope="col">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($private as $priv)
                                <tr>
                                    <th>{{$priv->id}}</th>
                                    <th>{{$priv->title}}</th>
                                    <th>
                                        <div class="col-md-12">
                                            <div class="col-md-2">
                                                <form method="GET" action="{{route('kanban.show', ['id' => $priv->id])}}">
                                                    <button type="submit" class="btn btn-default">Accéder</button>
                                                </form>
                                            </div>
                                            <div class="col-md-2">
                                                <form method="GET" action="{{route('kanban.edit', ['id' => $priv->id])}}">
                                                    <button type="submit" class="btn btn-warning">Editer</button>
                                                </form>
                                            </div>
                                            <div class="col-md-2">
                                                {!! Form::open([
                                                    'method' => 'DELETE',
                                                    'route' => ['kanban.destroy', $priv->id]]) !!}
                                                {!! Form::submit('Suppression', ['class' => 'btn btn-danger']) !!}
                                                {!! Form::close() !!}
                                            </div>
                                        </div>
                                    </th>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Kanbans où je suis invité
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nom</th>
                                <th scope="col">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($invited as $inv)
                                <tr>
                                    <th>{{$inv->id}}</th>
                                    <th>{{$inv->title}}</th>
                                    <th>
                                        <div class="col-md-1 action_btn">
                                            <form method="GET" action="{{route('kanban.show', ['id' => $inv->id])}}">
                                                <button type="submit" class="btn btn-default">Accéder</button>
                                            </form>
                                        </div>
                                    </th>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                @endif
                <div class="panel panel-default">
                    <div class="panel-heading">Kanbans publics de {{$user->name}}</div>
                    <div class="panel-body">
                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nom</th>
                                <th scope="col">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($public as $pub)
                                <tr>
                                    <th>{{$pub->id}}</th>
                                    <th>{{$pub->title}}</th>
                                    <th>
                                        <div class="col-md-12">
                                            <div class="col-md-2">
                                                <form method="GET" action="{{route('kanban.show', ['id' => $pub->id])}}">
                                                    <button type="submit" class="btn btn-default">Accéder</button>
                                                </form>
                                            </div>
                                            @if(Auth::id() == $user->id)
                                                <div class="col-md-2">
                                                    <form method="GET" action="{{route('kanban.edit', ['id' => $pub->id])}}">
                                                        <button type="submit" class="btn btn-warning">Editer</button>
                                                    </form>
                                                </div>
                                                <div class="col-md-2">
                                                    {!! Form::open([
                                                        'method' => 'DELETE',
                                                        'route' => ['kanban.destroy', $pub->id]]) !!}
                                                    {!! Form::submit('Suppression', ['class' => 'btn btn-danger']) !!}
                                                    {!! Form::close() !!}
                                                </div>
                                            @endif
                                    </th>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @if(Auth::id() == $user->id)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Mes tâches :
                        </div>
                        <div class="panel-body">
                            <table class="table">
                                <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Titre</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">A faire pour</th>
                                    <th scope="col">Kanban associé</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($cards as $card)
                                    <tr>
                                        <th scope="row">{{$card->id}}</th>
                                        <td>{{$card->title}}</td>
                                        <td>{{$card->description}}</td>
                                        <td>{{$card->end_at}}</td>
                                        <td>
                                            <a href="{{route("kanban.show", $kanbans[$card->column_id])}}">{{$kanbans_names[$card->column_id]}}</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
@stop